collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "robotinobase3/base_link"
    odom_frame_id: "robotinobase3/odom"
    cmd_vel_in_topic: "/robotinobase3/cmd_vel_smoothed"
    cmd_vel_out_topic: "/robotinobase3/cmd_vel"
    state_topic: "/robotinobase3/cm_state"
    transform_tolerance: 0.1
    source_timeout: 5.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop" and "slowdown" action types,
    # and robot footprint for "approach" action type.
    # Footprint could be "polygon" type with dynamically set footprint from footprint_topic
    # or "circle" type with static footprint set by radius. "footprint_topic" parameter
    # to be ignored in circular case.
    polygons: ["PolygonStop, PolygonSlow"]
    PolygonStop:
      type: "circle"
      radius: 0.280
      action_type: "stop"
      max_points: 2
      visualize: True
      polygon_pub_topic: "/robotinobase3/polygon_stop"
      enable: True
    PolygonSlow:
      type: "circle"
      radius: 0.350
      action_type: "slowdown"
      max_points: 2
      slowdown_ratio: 0.3
      visualize: True
      polygon_pub_topic: "/robotinobase3/polygon_slowdown"
      enable: True
    # FootprintApproach:
    #   type: "polygon"
    #   action_type: "approach"
    #   footprint_topic: "/local_costmap/published_footprint"
    #   time_before_collision: 2.0
    #   simulation_time_step: 0.1
    #   max_points: 5
    #   visualize: False
    observation_sources: ["scan"]
    scan:
      source_timeout: 0.2
      type: "scan"
      topic: "/robotinobase3/ir_scan_merged"
      enabled: True
    pointcloud:
      type: "pointcloud"
      topic: "/intel_realsense_r200_depth/points"
      min_height: 0.1
      max_height: 0.5

