costmap_filter_info_server:
  ros__parameters:
    use_sim_time: true
    type: 0
    filter_info_topic: "/robotinobase1/costmap_filter_info"
    mask_topic: "/robotinobase1/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

filter_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/robotinobase1/keepout_filter_mask"
    yaml_filename: "filter_mask.yaml"
