/**:
  ros__parameters:
    static_transforms:
      A_TIM:
        translation: [-23.845, -0.979, 0.0]
        rotation: [-1.57079632679, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "TIM"
      A_SS1:
        translation: [-17.76, -1.01, 0.0]
        rotation: [-1.57079632679, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "A_SS1"

      A_SS2:
        translation: [-19.54, -0.67, 0.0]
        rotation: [3.14159265359, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "A_SS2"

      A_WB1:
        translation: [-19.35, 3.01, 0.0]
        rotation: [3.14159265359, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "A_WB1"

      A_WB2:
        translation: [-18.31, 4.03, 0.0]
        rotation: [1.57079632679, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "A_WB2"

      A_CC:
        translation: [-15.63, 5.03, 0.0]
        rotation: [1.57079632679, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "A_CC"

      B_SS1:
        translation: [-11.37, -0.92, 0.0]
        rotation: [-1.57079632679, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "B_SS1"

      B_SS2:
        translation: [-9.57, -0.68, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "B_SS2"

      B_WB1:
        translation: [-9.55, 2.97, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "B_WB1"

      B_WB2:
        translation: [-11.35, 4.03, 0.0]
        rotation: [1.57079632679, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "B_WB2"

      B_CC:
        translation: [-13.49, 4.88, 0.0]
        rotation: [1.57079632679, 0.0, 0.0]
        parent_frame_id: "map"
        child_frame_id: "B_CC"

      A_SS1_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_SS1"
        child_frame_id: "A_SS1-LEFT"

      A_SS1_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_SS1"
        child_frame_id: "A_SS1-RIGHT"

      A_SS2_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_SS2"
        child_frame_id: "A_SS2-LEFT"

      A_SS2_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_SS2"
        child_frame_id: "A_SS2-RIGHT"

      A_WB1_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_WB1"
        child_frame_id: "A_WB1-LEFT"

      A_WB1_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_WB1"
        child_frame_id: "A_WB1-RIGHT"

      A_WB2_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_WB2"
        child_frame_id: "A_WB2-LEFT"

      A_WB2_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_WB2"
        child_frame_id: "A_WB2-RIGHT"

      A_CC_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_CC"
        child_frame_id: "A_CC-LEFT"

      A_CC_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "A_CC"
        child_frame_id: "A_CC-RIGHT"

      B_SS1_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_SS1"
        child_frame_id: "B_SS1-LEFT"

      B_SS1_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_SS1"
        child_frame_id: "B_SS1-RIGHT"

      B_SS2_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_SS2"
        child_frame_id: "B_SS2-LEFT"

      B_SS2_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_SS2"
        child_frame_id: "B_SS2-RIGHT"

      B_WB1_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_WB1"
        child_frame_id: "B_WB1-LEFT"

      B_WB1_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_WB1"
        child_frame_id: "B_WB1-RIGHT"

      B_WB2_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_WB2"
        child_frame_id: "B_WB2-LEFT"

      B_WB2_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_WB2"
        child_frame_id: "B_WB2-RIGHT"

      B_CC_LEFT:
        translation: [0.0, 0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_CC"
        child_frame_id: "B_CC-LEFT"

      B_CC_RIGHT:
        translation: [0.0, -0.20, 0.0]
        rotation: [0.0, 0.0, 0.0]
        parent_frame_id: "B_CC"
        child_frame_id: "B_CC-RIGHT"
