amcl:
  ros__parameters:
    base_frame_id: "robotinobase2/base_link"
    odom_frame_id: "robotinobase2/odom"
    scan_topic: /robotinobase2/fawkes_scans/Laser_urg_filtered_360

    robot_model_type: "nav2_amcl::OmniMotionModel"

    # values from fawkes AMCL
    # alpha values
    alpha1: 1.0
    alpha2: 1.0
    alpha3: 0.4
    alpha4: 0.4
    alpha5: 0.4

    # beam skip is disabled by default
    # do_beamskip: true
    # beam_skip_distance: 0.3

    # laser
    laser_likelihood_max_dist: 8.5
    laser_max_range: 15.0
    laser_min_range: 0.05

    # beam model
    lambda_short: 0.1
    max_beams: 120
    max_particles: 1000
    min_particles: 500

    # movement update settings
    update_min_a: 0.05
    update_min_d: 0.1

    # priori probabilities
    z_hit: 0.95
    sigma_hit: 0.2
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.05

bt_navigator:
  ros__parameters:
    robot_base_frame: robotinobase2/base_link
    odom_topic: "/robotinobase2/odom_filtered"

controller_server:
  ros__parameters:
    odom_topic: "/robotinobase2/odom_filtered"

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: robotinobase2/odom
      robot_base_frame: robotinobase2/base_link
      obstacle_layer:
        scan:
          topic: /robotinobase2/fawkes_scans/Laser_urg_filtered_360

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: robotinobase2/base_link
      obstacle_layer:
        scan:
          topic: /robotinobase2/fawkes_scans/Laser_urg_filtered_360

map_server:
  ros__parameters:
    yaml_filename: "/home/srb-jarvis/ros2_ws/ws_thesis/simulation_ws/src/rcll_simulation_webots/robotino3_navigation/map/map.yaml"

behavior_server:
  ros__parameters:
    costmap_topic: /robotinobase2/local_costmap/costmap_raw
    footprint_topic: /robotinobase2/local_costmap/published_footprint
    robot_base_frame: robotinobase2/base_link


velocity_smoother:
  ros__parameters:
    odom_topic: "/robotinobase2/odom_filtered"

collision_monitor:
  ros__parameters:
    base_frame_id: "robotinobase2/base_link"
    odom_frame_id: "robotinobase2/odom"
    cmd_vel_in_topic: "/robotinobase2/cmd_vel_smoothed"
    cmd_vel_out_topic: "/robotinobase2/cmd_vel"
    state_topic: "/robotinobase2/cm_state"
    PolygonStop:
      polygon_pub_topic: "/robotinobase2/polygon_stop"
    PolygonSlow:
      polygon_pub_topic: "/robotinobase2/polygon_slowdown"
    scan:
      topic: "/robotinobase2/fawkes_scans/Laser_urg_filtered_360"
