amcl:
  ros__parameters:
    base_frame_id: "robotinobase3/base_link"
    odom_frame_id: "robotinobase3/odom"
    scan_topic: /robotinobase3/scan

bt_navigator:
  ros__parameters:
    robot_base_frame: robotinobase3/base_link
    odom_topic: "/robotinobase3/odom"

controller_server:
  ros__parameters:
    odom_topic: "/robotinobase3/odom"

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: robotinobase3/odom
      robot_base_frame: robotinobase3/base_link
      obstacle_layer:
        scan:
          topic: /robotinobase3/scan

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: robotinobase3/base_link
      obstacle_layer:
        scan:
          topic: /robotinobase3/scan

behavior_server:
  ros__parameters:
    costmap_topic: /robotinobase3/local_costmap/costmap_raw
    footprint_topic: /robotinobase3/local_costmap/published_footprint
    robot_base_frame: robotinobase3/base_link

velocity_smoother:
  ros__parameters:
    odom_topic: "/robotinobase3/odom_filtered"

collision_monitor:
  ros__parameters:
    base_frame_id: "robotinobase3/base_link"
    odom_frame_id: "robotinobase3/odom"
    cmd_vel_in_topic: "/robotinobase3/cmd_vel_smoothed"
    cmd_vel_out_topic: "/robotinobase3/cmd_vel"
    state_topic: "/robotinobase3/cm_state"
    PolygonStop:
      polygon_pub_topic: "/robotinobase3/polygon_stop"
    PolygonSlow:
      polygon_pub_topic: "/robotinobase3/polygon_slowdown"
    scan:
      topic: "/robotinobase3/ir_scan_merged"
