# Minimal robot-specific configuration for robotinobase1
# Only contains parameters that are truly unique per robot

amcl:
  ros__parameters:
    # Robot-specific initial pose
    initial_pose:
      x: 5.5
      y: 0.45
      z: 0.0
      yaw: 3.14
