amcl:
  ros__parameters:
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: /scan

bt_navigator:
  ros__parameters:
    robot_base_frame: base_link
    odom_topic: "/odom"

controller_server:
  ros__parameters:
    odom_topic: "/odom"

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      obstacle_layer:
        scan:
          topic: /scan

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: base_link
      obstacle_layer:
        scan:
          topic: /scan

behavior_server:
  ros__parameters:
    costmap_topic: /local_costmap/costmap_raw
    footprint_topic: /local_costmap/published_footprint
    robot_base_frame: base_link

velocity_smoother:
  ros__parameters:
    odom_topic: "/odom_filtered"

collision_monitor:
  ros__parameters:
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "/cmd_vel_smoothed"
    cmd_vel_out_topic: "/cmd_vel"
    state_topic: "/cm_state"
    PolygonStop:
      polygon_pub_topic: "/polygon_stop"
    PolygonSlow:
      polygon_pub_topic: "/polygon_slowdown"
    scan:
      topic: "/ir_scan_merged"
