collision_monitor:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_raw"
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 0.1
    source_timeout: 0.5
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop" and "slowdown" action types,
    # and robot footprint for "approach" action type.
    # Footprint could be "polygon" type with dynamically set footprint from footprint_topic
    # or "circle" type with static footprint set by radius. "footprint_topic" parameter
    # to be ignored in circular case.
    polygons: ["PolygonSlow"]
    #PolygonStop:
     # type: "circle"
     # radius: 0.300
     # action_type: "stop"
     # max_points: 20
     # visualize: True
     # polygon_pub_topic: "polygon_stop"
    PolygonSlow:
     type: "circle"
     radius: 0.450
     action_type: "slowdown"
     max_points: 10
     slowdown_ratio: 0.2
     visualize: True
     polygon_pub_topic: "polygon_slowdown"
    #PolygonLimit:
    # type: "polygon"
    # points: [0.5, 0.5, 0.5, -0.5, -0.5, -0.5, -0.5, 0.5]
    # action_type: "limit"
    # max_points: 10  # max_points: 3 for Humble
    # linear_limit: 0.5
    # angular_limit: 0.5
    # visualize: True
    # polygon_pub_topic: "polygon_limit"
    # FootprintApproach:
    #     type: "polygon"
    #     action_type: "approach"
    #     footprint_topic: "/local_costmap/published_footprint"
    #     time_before_collision: 2.0
    #     simulation_time_step: 0.1
    #     max_points: 5
    #     visualize: False
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/fawkes_scans/Laser_urg_filtered_360"
      observation_sources: ["scan"]
    # scan:
    #   type: "scan"
    #   topic: "/fawkes_scans/Laser_urg_filtered_360"
    # pointcloud:
    #   type: "pointcloud"
    #   topic: "/intel_realsense_r200_depth/points"
    #   min_height: 0.1
    #   max_height: 0.5
