---
front_laser:
    ros__parameters:
      frame_id:  robotinobase4/front_laser_link
      hostname: 192.168.0.42
      port: 2112
back_laser:
    ros__parameters:
      frame_id:  robotinobase4/back_laser_link
      hostname: 192.168.0.43
      port: 2112
static_transforms:
  front_laser:
    child_frame_id: robotinobase4/front_laser_link
    parent_frame_id: robotinobase4/base_link
  back_laser:
    child_frame_id: robotinobase4/back_laser_link
    parent_frame_id: robotinobase4/base_link
  laser:
    child_frame_id: robotinobase4/laser_link
    parent_frame_id: robotinobase4/base_link
