---
/front/front_laser:
  ros__parameters:
    frame_id: front_laser_link
    hostname: "192.168.0.42"
    port: "2112"
/back/rear_laser:
  ros__parameters:
    frame_id: back_laser_link
    hostname: "192.168.0.43"
    port: "2112"
/**:
  ros__parameters:
    static_transforms:
      front_laser:
        child_frame_id: front_laser_link
        parent_frame_id: base_link
      back_laser:
        child_frame_id: back_laser_link
        parent_frame_id: base_link
      laser:
        child_frame_id: laser_link
        parent_frame_id: base_link
